image: docker:git
services:
- docker:dind

before_script:
  - docker login -u $CI_BUILD_USERNAME -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

build_alpine:
  script:
## Gitlab Hub : registry.gitlab.com
    - docker build -t registry.gitlab.com/maro4inter/openshift:kafka ./
###    - docker push registry.gitlab.com/maro4inter/openshift:kafka
    - docker tag registry.gitlab.com/maro4inter/openshift:kafka $DOCKER_HUB_USERNAME/openshift:kafka
## Docker Hub
    - docker push $DOCKER_HUB_USERNAME/openshift:kafka
  only:
    - master